### ISSUE TITLE
No hay ningun codigo

### ISSUE THREAD

**Issue by brunocar** [argob/cuidar#1]
No hay codigo, nisiquiera un readme, que pasó?

**Comment by cuidarapp** [comment]
El código se subirá en los próximos días.

**Comment by hellocoldworld** [comment]
Alguna novedad? Cerraron esta incidencia hace 29 días y aún no hay código

**Comment by Oppen** [comment]
Más de un mes desde el último comment y sin respuesta. Pueden comentar al menos por qué no se hace?
