### ISSUE TITLE
El app trackea infectados con síntomas, pero la transmisión se da también en infectados asintomáticos.

### ISSUE THREAD

**Issue by ortegaalfredo** [argob/cuidar#5]
El app busca identificar infectados con Covid-19 realizando un cuestionario donde se identifican síntomas, sin embargo, aun suponiendo que los individuos respondan honestamente, una gran parte de las infecciones son via infectados asintomáticos, que el app no puede detectar. Cita:

"live coronavirus clearly sheds at high concentrations from the nasal cavity even before symptom development" de "Asymptomatic Transmission, the Achilles’ Heel of Current Strategies to Control Covid-19"  Monica Gandhi, M.D., M.P.H., Deborah S. Yokoe, M.D., M.P.H., and Diane V. Havlir, M.D.

https://www.nejm.org/doi/full/10.1056/NEJMe2009758

**Comment by cuidarapp** [comment]
La aplicación no es la única herramienta que utiliza el sistema de salud argentino.
Este tracker se utilizará sólo para temas relacionados con el código. El resto de las consultas pueden evacuarse en https://www.argentina.gob.ar/aplicaciones/coronavirus/contanos-sobre-la-app-cuidar-covid-19
